import Link from "next/link";
import type { Folder, Note, Product, Project } from "@/data/mock-data";

export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="mb-3 font-mono text-[11px] font-bold uppercase tracking-[0.2em] text-primary-600">{children}</p>; }
export function SectionHeading({ title, description, href, linkLabel = "View all" }: { title: string; description?: string; href?: string; linkLabel?: string }) { return <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-bold tracking-tight text-neutral-950 sm:text-3xl">{title}</h2>{description && <p className="mt-2 max-w-xl text-sm leading-6 text-neutral-500">{description}</p>}</div>{href && <Link href={href} className="text-sm font-semibold text-primary-700 hover:text-primary-900">{linkLabel} <span aria-hidden="true">→</span></Link>}</div>; }
export function StatusBadge({ status }: { status: string }) { const styles: Record<string, string> = { published: "bg-success-50 text-success-700", maintenance: "bg-warning-50 text-warning-700", draft: "bg-neutral-100 text-neutral-500", archived: "bg-neutral-100 text-neutral-500", "In development": "bg-primary-50 text-primary-700", Prototype: "bg-warning-50 text-warning-700", Exploring: "bg-neutral-100 text-neutral-600", "In stock": "bg-success-50 text-success-700", "Low stock": "bg-warning-50 text-warning-700", "Sold out": "bg-error-50 text-error-700" }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold ${styles[status] ?? "bg-neutral-100 text-neutral-600"}`}>{status}</span>; }
const folderAccentClasses: Record<string, string> = { amber: "bg-accent-50", green: "bg-success-50", blue: "bg-primary-50", slate: "bg-neutral-100" };

export function FolderCard({ folder, basePath }: { folder: Folder; basePath: string }) { const open = folder.status === "published"; const accentClass = folderAccentClasses[folder.accent] ?? folderAccentClasses.blue; return <div className="group relative overflow-hidden rounded-2xl border border-neutral-200 bg-white p-6 shadow-sm transition-all hover:-translate-y-1 hover:border-primary-200 hover:shadow-lg"><div className={`absolute right-0 top-0 h-24 w-24 rounded-bl-full ${accentClass}`} /><div className="relative"><div className="mb-8 flex items-center justify-between"><span className="text-2xl">{folder.accent === "amber" ? "✦" : folder.accent === "green" ? "⌁" : "#"}</span><StatusBadge status={folder.status} /></div>{open ? <Link href={`${basePath}/${folder.slug}`} className="block"><h3 className="text-lg font-bold text-neutral-900 group-hover:text-primary-700">{folder.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-neutral-500">{folder.description}</p><p className="mt-5 font-mono text-[11px] uppercase tracking-wider text-neutral-400">{folder.count} entries <span className="ml-1 text-primary-600">↗</span></p></Link> : <div><h3 className="text-lg font-bold text-neutral-900">{folder.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-neutral-500">{folder.description}</p><p className="mt-5 font-mono text-[11px] uppercase tracking-wider text-warning-700">Temporarily closed</p></div>}</div></div>; }
export function NoteCard({ note }: { note: Note }) { return <Link href={`/note/${note.folderSlug}/${note.slug}`} className="group block border-t border-neutral-200 py-5"><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold text-neutral-900 transition-colors group-hover:text-primary-700">{note.title}</h3><p className="mt-2 text-sm leading-6 text-neutral-500">{note.excerpt}</p><div className="mt-3 flex gap-2">{note.tags.map((tag) => <span key={tag} className="font-mono text-[10px] uppercase tracking-wider text-primary-600">#{tag}</span>)}</div></div><span className="pt-1 text-neutral-300 transition-transform group-hover:translate-x-1 group-hover:text-primary-500">→</span></div><p className="mt-4 font-mono text-[10px] uppercase tracking-wider text-neutral-400">{note.date} · {note.readTime}</p></Link>; }
export function ProjectCard({ project }: { project: Project }) { return <Link href={`/project/${project.folderSlug}/${project.slug}`} className="group overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm transition-all hover:-translate-y-1 hover:shadow-lg"><div className="aspect-[4/3] overflow-hidden bg-neutral-100"><img src={project.image} alt="" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" /></div><div className="p-5"><div className="mb-3 flex items-center justify-between gap-3"><StatusBadge status={project.status} /><span className="text-neutral-300 transition-transform group-hover:translate-x-1 group-hover:text-primary-500">→</span></div><h3 className="font-bold text-neutral-900 group-hover:text-primary-700">{project.title}</h3><p className="mt-2 text-sm leading-6 text-neutral-500">{project.description}</p></div></Link>; }
export function ProductCard({ product }: { product: Product }) { return <Link href={`/jualan/${product.folderSlug}/${product.slug}`} className="group overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm transition-all hover:-translate-y-1 hover:shadow-lg"><div className="relative aspect-[4/3] overflow-hidden bg-neutral-100"><img src={product.image} alt="" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" /><div className="absolute left-3 top-3 flex flex-wrap gap-1.5">{product.labels.map((label) => <span key={label} className="rounded-full bg-white/95 px-2.5 py-1 text-[10px] font-bold text-neutral-700 shadow-sm">{label}</span>)}</div></div><div className="p-5"><div className="mb-3 flex items-center justify-between"><StatusBadge status={product.stock} /><span className="font-mono text-xs text-neutral-700">{product.priceLabel}</span></div><h3 className="font-bold text-neutral-900 group-hover:text-primary-700">{product.name}</h3><p className="mt-2 text-sm leading-6 text-neutral-500">{product.description}</p></div></Link>; }


